# SPDX-License-Identifier: LGPL-2.1-or-later
#
# naudio — the C99 consumer gate. Driven by the `naudio_c99_header_gate` ctest arm; see the
# add_test() comment in the root CMakeLists.txt for why it exists (issue #45).
#
# Run as: cmake -D NA_CC=... -D NA_INCLUDE_DIR=... -D NA_SOURCE_DIR=... -D NA_WORK_DIR=... -P
#
# TWO ARMS, and the second is not decoration. The gate's own passing result is the ABSENCE of a
# compiler diagnostic, which is the shape most able to pass while measuring nothing: a wrong include
# path, a flag the front end quietly ignored, or a TU that never reached the compiler all report
# "clean" exactly as a conformant header does. So the same TU is compiled a second time with ONE
# C11 construct appended, and that arm must FAIL. Arm 2 proves the toolchain is really enforcing
# C99 and really parsing this file; only then does arm 1's silence mean anything.
#
# The control is generated by appending to consumer.c rather than kept as a second file on purpose:
# it pins the delta between the two arms at exactly one line, so a control failure cannot be
# attributed to anything but the C11-ism.

foreach(var NA_CC NA_INCLUDE_DIR NA_SOURCE_DIR NA_WORK_DIR)
    if(NOT DEFINED ${var} OR "${${var}}" STREQUAL "")
        message(FATAL_ERROR "c99-header-gate: ${var} was not passed to the script")
    endif()
endforeach()

set(consumer "${NA_SOURCE_DIR}/consumer.c")
if(NOT EXISTS "${consumer}")
    message(FATAL_ERROR "c99-header-gate: ${consumer} is missing")
endif()

set(std_flags -std=c99 -pedantic-errors -fsyntax-only "-I${NA_INCLUDE_DIR}")
# CMake renders a list with ';' separators; every message below quotes the command line, so join
# it once here rather than shipping a semicolon-spattered diagnostic to whoever trips the gate.
string(JOIN " " cmdline "${NA_CC}" ${std_flags})
message(STATUS "c99-header-gate: ${cmdline}")

# ---------------------------------------------------------------------------
# Arm 1 — the gate. include/naudio.h must be C99-clean, as CMakeLists.txt and
# CONTRIBUTING.md both promise a consumer it is.
# ---------------------------------------------------------------------------
execute_process(
    COMMAND "${NA_CC}" ${std_flags} "${consumer}"
    RESULT_VARIABLE gate_rc
    OUTPUT_VARIABLE gate_out
    ERROR_VARIABLE gate_err)

if(NOT gate_rc EQUAL 0)
    # TWO causes reach this branch and the diagnostic must not name only one of them: the header
    # may have acquired a post-C99 construct, or consumer.c may itself be broken. Read the file
    # the compiler names below to tell them apart — a message that assumes the first reads as a
    # confident false accusation whenever it was the second.
    message(FATAL_ERROR
        "c99-header-gate: a translation unit including include/naudio.h did NOT compile at "
        "-std=c99 -pedantic-errors.\n"
        "WHICH FILE does the diagnostic below name?\n"
        "  include/naudio.h  — the header has gained a construct past C99, but CMakeLists.txt and "
        "CONTRIBUTING.md both promise a consumer it is C99-clean. Either revert that construct, or "
        "RAISE the documented floor in BOTH of those files and say why — do not leave the claim "
        "and the header disagreeing (issue #45).\n"
        "  consumer.c        — the gate's own TU is broken; fix it there. It is deliberately "
        "welded to the header (it USES the ABI, so the #include cannot be silently dropped), which "
        "is also why an ABI rename can land here.\n"
        "--- ${cmdline} ---\n${gate_out}${gate_err}")
endif()

message(STATUS "c99-header-gate: ok   include/naudio.h is C99-clean")

# ---------------------------------------------------------------------------
# Arm 2 — the positive control. Same TU, one C11 construct appended. MUST fail;
# if it passes, arm 1's silence proves nothing about the header.
# ---------------------------------------------------------------------------
file(READ "${consumer}" consumer_text)
set(control "${NA_WORK_DIR}/consumer_c11_control.c")
file(WRITE "${control}"
     "${consumer_text}\n"
     "/* Appended by check.cmake: the ONE C11 construct that must be rejected at -std=c99. */\n"
     "_Static_assert(1, \"c99-header-gate positive control\");\n")

execute_process(
    COMMAND "${NA_CC}" ${std_flags} "${control}"
    RESULT_VARIABLE control_rc
    OUTPUT_VARIABLE control_out
    ERROR_VARIABLE control_err)

if(control_rc EQUAL 0)
    message(FATAL_ERROR
        "c99-header-gate: the positive control COMPILED. A _Static_assert is a C11 construct and "
        "must be rejected at -std=c99 -pedantic-errors, so this toolchain is not enforcing the "
        "level this gate claims to check — arm 1's clean result above measures nothing.\n"
        "Check that -std=c99 and -pedantic-errors survived to the front end.\n"
        "--- ${cmdline} ${control} ---\n${control_out}${control_err}")
endif()

message(STATUS "c99-header-gate: ok   the C11 control is rejected, so the level is enforced")
